### ISSUE TITLE
docs: sample repository for GitHub Actions

### ISSUE THREAD

**Issue by sayanee** [talos-systems/conform#147]
Is there a sample `.github/workflows/conform.yml` file or a repository that is using conform for GitHub Actions? [CI build seems to be failing for me](https://github.com/hutscape/pine/runs/253124435) because `base name (${GOLANG_IMAGE}) should not be blank`.

```yml
name: Conform
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Conform Action
      uses: talos-systems/conform@v0.1.0-alpha.16
      env:
        GOLANG_IMAGE: golang:1.12.6
```

**Comment by andrewrynhard** [comment]
Hi @sayanee. Unfortunately GitHub changed their format since the last time I have tested. One thing you could do is use our pre-built docker image (https://cloud.docker.com/u/autonomy/repository/docker/autonomy/conform) and skip GitHub building the container. I know maybe not the best answer, but its a workaround until I can test with the new actions format.

**Comment by sayanee** [comment]
Oops! Looks like it's giving me a `404` error:
![image](https://user-images.githubusercontent.com/413879/66537623-aa17a500-eb53-11e9-8756-4de09689cba9.png)

Yes, it does seem that the formatting for GitHub Actions is still in flux. I'm also unsure of the `yml` syntax to pull a custom pre-built docker image (after some brief searching). Maybe I'll wait for a few more months until things are more stable.

Thanks a lot for this tool 🙏 I'm using it locally with `conform enforce` and it works great!

**Comment by andrewrynhard** [comment]
@sayanee looks like you can do

```
uses: docker://autonomy/conform:v0.1.0-alpha.16
```

Reference: https://help.github.com/en/articles/workflow-syntax-for-github-actions

**Comment by sayanee** [comment]
Thanks, @andrewrynhard! The docker pull seems to be successful now. 

But [there's an error](https://github.com/hutscape/pine/runs/254609846) on `.conform.yaml` not found even though the file exists on the root of the repository. 

```
open .conform.yaml: no such file or directory
##[error]Docker run failed with exit code 1
```

The complete `.github/workflows/conform.yml file` now looks like:

```yml
name: Conform
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Conform Action
      uses: docker://autonomy/conform:v0.1.0-alpha.16
```

Am I missing something minor? 🤔

**Comment by andrewrynhard** [comment]
Looks like the working directory needs to be set? A local run seems to work just fine. This is likely something in the action definition that needs to be fixed.

```
[I] /t/scratch $ git clone https://github.com/hutscape/pine.git
Cloning into 'pine'...
remote: Enumerating objects: 386, done.
remote: Counting objects: 100% (386/386), done.
remote: Compressing objects: 100% (247/247), done.
remote: Total 726 (delta 225), reused 272 (delta 120), pack-reused 340
Receiving objects: 100% (726/726), 10.92 MiB | 1.31 MiB/s, done.
Resolving deltas: 100% (382/382), done.
[I] /t/scratch $ docker run --rm -v $PWD:/src/ -w /src autonomy/conform:0.1.0-alpha.16
Unable to find image 'autonomy/conform:0.1.0-alpha.16' locally
docker: Error response from daemon: manifest for autonomy/conform:0.1.0-alpha.16 not found: manifest unknown: manifest unknown.
See 'docker run --help'.
[I] /t/scratch $ docker run --rm -v $PWD:/src/ -w /src autonomy/conform:v0.1.0-alpha.16
Unable to find image 'autonomy/conform:v0.1.0-alpha.16' locally
v0.1.0-alpha.16: Pulling from autonomy/conform
20ca0f86a434: Pull complete
7af7ff28817f: Pull complete
Digest: sha256:f3ceb30f6a7a93a582bc3ecf66b15037773b72fb4f0b374b24c04bb54dfc38b0
Status: Downloaded newer image for autonomy/conform:v0.1.0-alpha.16
open .conform.yaml: no such file or directory
[I] /t/scratch $ cd pine/
[I] /t/s/pine master (a39dad2) $ docker run --rm -v $PWD:/src/ -w /src autonomy/conform:v0.1.0-alpha.16
POLICY        CHECK                      STATUS        MESSAGE
commit        Conventional Commit        PASS          <none>
```

**Comment by jwnx** [comment]
@sayanee I was able to fix by calling [actions/checkout](https://github.com/actions/checkout) first (:

```
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Conform Action
      uses: docker://autonomy/conform:v0.1.0-alpha.16
```
